site_name: Jupygrader Documentation

theme:
  name: material
  logo: images/logo_small_icon.png
  favicon: images/favicon.png
  palette:
    primary: blue grey

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
  - Update Docs: docs.md

plugins:
  - search
  - mkdocstrings # For API documentation

# Repository
repo_name: subwaymatch/jupygrader
repo_url: https://github.com/subwaymatch/jupygrader
