# Code Generated by Jupygrader
# TEST_CASE_METADATA_REPLACE_HERE
try:
    _did_pass = True
    _error_message = ''
# TEST_CASE_REPLACE_HERE
except BaseException as ex:
    _did_pass = False
    _error_message = type(ex).__name__ + ': ' + str(ex)
    raise
finally:
    _record_test_case(_test_case, _did_pass, _points, _error_message)